[workspace]
authors = ["pedestrianlove <jsli@linux.com>"]
channels = ["conda-forge"]
name = "urdf-anything"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
CUDA_HOME = "$CONDA_PREFIX"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib"

[tasks]

[dependencies]
python = "3.12.*"
cuda = "12.6.*"
cuda-toolkit = "*"
gcc = "*"

[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://download.pytorch.org/whl/cu126"]
find-links = [{url = "https://data.pyg.org/whl/torch-2.11.0+cu126.html"}]
no-build-isolation = ["diso"]

[pypi-dependencies]
torch = { version = ">=2.11.0" }
torchvision = { version = "*" }
torch-cluster = { version = "*" }
diso = { version = "*" }
